-- SAFE VIRTUAL REWARD MODEL
-- MYC = virtual/non-cashable points. Do not connect this to cash deposits or fixed financial returns.

create table if not exists public.ms_virtual_packages(
 id bigint generated by default as identity primary key, code text unique not null,
 name text not null, price_myc numeric(18,4) not null check(price_myc>0),
 mining_power integer not null check(mining_power>0), duration_days integer not null default 30 check(duration_days=30), active boolean not null default true);

create table if not exists public.ms_virtual_wallets(
 user_id uuid primary key references auth.users(id) on delete cascade,
 balance_myc numeric(18,4) not null default 0 check(balance_myc>=0),
 lifetime_earned_myc numeric(18,4) not null default 0,
 lifetime_spent_myc numeric(18,4) not null default 0, created_at timestamptz default now(), updated_at timestamptz default now());

create table if not exists public.ms_mining_contracts(
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 package_id bigint not null references public.ms_virtual_packages(id), started_at timestamptz default now(),
 ends_at timestamptz not null, last_claim_at timestamptz default now(), total_mined_myc numeric(18,4) default 0,
 status text default 'active' check(status in('active','completed','cancelled')));

create table if not exists public.ms_virtual_transactions(
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 tx_type text not null,amount_myc numeric(18,4) not null,balance_after_myc numeric(18,4) not null,
 reference_id text,description text not null,created_at timestamptz default now());

create table if not exists public.ms_referral_codes(user_id uuid primary key references auth.users(id) on delete cascade,referral_code text unique not null,created_at timestamptz default now());
create table if not exists public.ms_referrals(id bigint generated by default as identity primary key,referrer_id uuid not null references auth.users(id) on delete cascade,referred_id uuid unique not null references auth.users(id) on delete cascade,referral_code text not null,verified_at timestamptz,qualifying_missions integer default 0,created_at timestamptz default now(),check(referrer_id<>referred_id));

insert into public.ms_virtual_packages(code,name,price_myc,mining_power,duration_days) values
('MS100','Paket Virtual 100 MYC',100,10,30),('MS200','Paket Virtual 200 MYC',200,25,30),
('MS300','Paket Virtual 300 MYC',300,40,30),('MS400','Paket Virtual 400 MYC',400,60,30)
on conflict(code) do update set name=excluded.name,price_myc=excluded.price_myc,mining_power=excluded.mining_power,duration_days=30,active=true;

alter table public.ms_virtual_packages enable row level security;
alter table public.ms_virtual_wallets enable row level security;
alter table public.ms_mining_contracts enable row level security;
alter table public.ms_virtual_transactions enable row level security;
alter table public.ms_referral_codes enable row level security;
alter table public.ms_referrals enable row level security;

revoke all on public.ms_virtual_packages,public.ms_virtual_wallets,public.ms_mining_contracts,public.ms_virtual_transactions,public.ms_referral_codes,public.ms_referrals from anon,authenticated;
grant select on public.ms_virtual_packages,public.ms_virtual_wallets,public.ms_mining_contracts,public.ms_virtual_transactions,public.ms_referral_codes,public.ms_referrals to authenticated;

drop policy if exists ms_pkg_read on public.ms_virtual_packages;
create policy ms_pkg_read on public.ms_virtual_packages for select to authenticated using(active=true);
drop policy if exists ms_wallet_read on public.ms_virtual_wallets;
create policy ms_wallet_read on public.ms_virtual_wallets for select to authenticated using(user_id=auth.uid());
drop policy if exists ms_contract_read on public.ms_mining_contracts;
create policy ms_contract_read on public.ms_mining_contracts for select to authenticated using(user_id=auth.uid());
drop policy if exists ms_tx_read on public.ms_virtual_transactions;
create policy ms_tx_read on public.ms_virtual_transactions for select to authenticated using(user_id=auth.uid());
drop policy if exists ms_code_read on public.ms_referral_codes;
create policy ms_code_read on public.ms_referral_codes for select to authenticated using(user_id=auth.uid());
drop policy if exists ms_ref_read on public.ms_referrals;
create policy ms_ref_read on public.ms_referrals for select to authenticated using(referrer_id=auth.uid() or referred_id=auth.uid());

create or replace function public.ms_ensure_wallet() returns void language plpgsql security definer set search_path='' as $$
begin if auth.uid() is null then raise exception 'Not authenticated'; end if;
insert into public.ms_virtual_wallets(user_id) values(auth.uid()) on conflict do nothing; end $$;

create or replace function public.ms_get_referral_code() returns text language plpgsql security definer set search_path='' as $$
declare c text; begin if auth.uid() is null then raise exception 'Not authenticated'; end if;
select referral_code into c from public.ms_referral_codes where user_id=auth.uid();
if c is null then c='MS'||upper(substr(replace(auth.uid()::text,'-',''),1,8)); insert into public.ms_referral_codes(user_id,referral_code) values(auth.uid(),c) on conflict do nothing; end if; return c; end $$;

create or replace function public.ms_activate_package(p_package_id bigint) returns bigint language plpgsql security definer set search_path='' as $$
declare price numeric; bal numeric; cid bigint; begin if auth.uid() is null then raise exception 'Not authenticated'; end if; perform public.ms_ensure_wallet();
select price_myc into price from public.ms_virtual_packages where id=p_package_id and active=true and duration_days=30;
if price is null then raise exception 'Package tidak ditemukan'; end if;
update public.ms_virtual_wallets set balance_myc=balance_myc-price,lifetime_spent_myc=lifetime_spent_myc+price,updated_at=now()
where user_id=auth.uid() and balance_myc>=price returning balance_myc into bal;
if bal is null then raise exception 'Saldo MYC virtual tidak cukup'; end if;
insert into public.ms_mining_contracts(user_id,package_id,started_at,ends_at) values(auth.uid(),p_package_id,now(),now()+interval '30 days') returning id into cid;
insert into public.ms_virtual_transactions(user_id,tx_type,amount_myc,balance_after_myc,reference_id,description) values(auth.uid(),'package_activation',-price,bal,cid::text,'Aktivasi paket mining virtual 30 hari'); return cid; end $$;

create or replace function public.ms_claim_mining(p_contract_id bigint) returns numeric language plpgsql security definer set search_path='' as $$
declare power integer; ending timestamptz; lastc timestamptz; reward numeric; bal numeric; st text; begin
if auth.uid() is null then raise exception 'Not authenticated'; end if; perform public.ms_ensure_wallet();
select p.mining_power,c.ends_at,c.last_claim_at,c.status into power,ending,lastc,st from public.ms_mining_contracts c join public.ms_virtual_packages p on p.id=c.package_id where c.id=p_contract_id and c.user_id=auth.uid() for update;
if power is null then raise exception 'Contract tidak ditemukan'; end if; if st<>'active' then raise exception 'Contract tidak aktif'; end if;
reward=round(greatest(0,extract(epoch from(least(now(),ending)-lastc))/3600.0)*power*0.02,4);
if reward<=0 then return 0; end if;
update public.ms_mining_contracts set last_claim_at=least(now(),ending),total_mined_myc=total_mined_myc+reward,status=case when now()>=ending then 'completed' else 'active' end where id=p_contract_id;
update public.ms_virtual_wallets set balance_myc=balance_myc+reward,lifetime_earned_myc=lifetime_earned_myc+reward,updated_at=now() where user_id=auth.uid() returning balance_myc into bal;
insert into public.ms_virtual_transactions(user_id,tx_type,amount_myc,balance_after_myc,reference_id,description) values(auth.uid(),'mining_reward',reward,bal,p_contract_id::text,'Reward mining virtual'); return reward; end $$;

revoke execute on function public.ms_ensure_wallet() from public,anon;
revoke execute on function public.ms_get_referral_code() from public,anon;
revoke execute on function public.ms_activate_package(bigint) from public,anon;
revoke execute on function public.ms_claim_mining(bigint) from public,anon;
grant execute on function public.ms_ensure_wallet() to authenticated;
grant execute on function public.ms_get_referral_code() to authenticated;
grant execute on function public.ms_activate_package(bigint) to authenticated;
grant execute on function public.ms_claim_mining(bigint) to authenticated;
